### ISSUE TITLE
An error occurs in Step 2, stating "No module named 'norm.norm_data_processing'".

### ISSUE THREAD

**Issue by zhouzhengqd** [sxswz213/CRSEC#1]
I noticed that the 'norm_data_processing.py' file is missing from the norm folder in your code repository. This seems to be causing an error in Step 2. Just thought I'd bring it to your attention.

**Comment by sxswz213** [comment]
Thank you for raising this issue! The 'norm_data_processing.py' file is not utilized in the current version of our code. We have updated the code and resubmitted it. To resolve this issue, you can either re-clone our repository or simply delete line 41, 'from norm.norm_data_processing import *', from the 'reverie.py' file which is located in reverie/backend_server.
